Feature/better docker diagnostics
7mind/izumi pull request #1132
Opened 2020-07-02 19:51 UTC by pshirshov

2020-07-03 09:14 UTC, Caparow approved these changes

2020-07-03 12:19 UTC, neko-kai requested changes

2020-07-03 12:19 UTC, neko-kai commented on distage/distage-framework-docker/src/main/scala/izumi/distage/docker/healthcheck/ContainerHealthCheck.scala
> +  final case class AvailablePorts(availablePorts: NonEmptyMap[DockerPort, NonEmptyList[AvailablePort]]) {
Being non-empty doesn't actually make this any safer since the `port` argument may still be missing from the map in all of the functions below.

2020-07-03 12:19 UTC, neko-kai commented on distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala
> +  availablePorts: Option[AvailablePorts],
This makes the API worse and doesn't actually increase safety. (see comment below) Could you please revert?

2020-07-07 22:37 UTC, neko-kai approved these changes

2020-07-08 18:55 UTC, merged