added missed info about rt and test artifacts
7mind/izumi pull request #425
Opened 2018-10-18 12:51 UTC by ratoshniuk

2018-10-18 12:55 UTC, neko-kai requested changes

2018-10-18 12:55 UTC, kaishh commented on doc/microsite/src/main/tut/sbt/00_sbt.md
> +Working with dependecies cross projects
typo

2018-10-18 12:55 UTC, kaishh commented on doc/microsite/src/main/tut/sbt/00_sbt.md
> +Imagine, you have a sdk project and you want to inclide one of it's library artifacts (i.e. target_libraty).
This should be a part of "Create a BOM for your projects" doc
https://github.com/pshirshov/izumi-r2/pull/425/files#diff-389e35bb33460e4d05c75d0a783571f9R248

2018-10-18 12:55 UTC, kaishh commented on doc/microsite/src/main/tut/sbt/00_sbt.md
> +### T
Merge all examples into one section, add the code they'll expand to.

2018-10-18 13:08 UTC, kaishh commented on doc/microsite/src/main/tut/sbt/00_sbt.md
> +Imagine, you have a sdk project and you want to inclide one of it's library artifacts (i.e. target_libraty).
Make it flow with previous content in the section, drop "imagine" – describe and include code samples for generated output of BOM plugin.

2018-10-18 18:44 UTC, kaishh commented on doc/microsite/src/main/tut/sbt/00_sbt.md
> +  YourSdk.R.my_project_bom,     // Runtime artifact
Make it consistent with the example given in lines above, e.g.:

```scala
MyProjectBOM.R.my_lib,     // Runtime dependency, same as `groupId %% "my-lib" % version`
MyProjectBOM.T.my_lib,     // Runtime dependency in for test scope, same as `groupId %% "my-lib" % version % Test`
```

add `import com.mycompany.myproject.MyProjectBOM`

And add an example `my_lib` project that `MyProjectBOM` exports

```scala
lazy val myLib = ...
```

2018-10-22 19:27 UTC, ratoshniuk commented
@kaishh check this out

2018-10-22 20:05 UTC, kaishh commented
> @kaishh check this out

LGTM

2018-10-22 20:05 UTC, kaishh commented
> @kaishh check this out

LGTM

2018-10-22 20:05 UTC, merged